

# This file was *autogenerated* from the file gif_maker.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_7 = Integer(7)
import os                                                                          
from sage.plot.colors import rainbow                                               
from functions import graphField, plotGraph, rightEdges, dynamics, makeimages, p   
K = GF(_sage_const_9 ,'a', names=('a',)); (a,) = K._first_ngens(1)
f = p([a,_sage_const_0 ,_sage_const_0 ,_sage_const_2 *a+_sage_const_1 ])          
elements = [x for x in K]                            
vs = graphField(K).vertices()                        
newelements = []                                     
for i in range(len(elements)):                       
   if str(elements[i]) != vs[i]:                     
       for b in elements:                            
           if str(b) == vs[i]:                       
               newelements.append(b)                 
   else:                                             
       newelements.append(elements[i])               
qs = []                                              
for c in newelements:                                
   qs += _sage_const_8 *[makeimages(K,f,c,figuresize=(_sage_const_7 ,_sage_const_7 ))[-_sage_const_1 ]]  
anim = animate(qs)                                   
anim.save(filename="gifs/[a,0,0,2*a+1]_9")                  
anim.ffmpeg(savefile="gifs/[a,0,0,2*a+1]_9.mpg")            

